### ISSUE TITLE
在xcode7.2.1中无法运行

### ISSUE THREAD

**Issue by medisean** [liuzechen/CCEaseRefresh#1]
在xcode7.2.1中，示例代码编译错误

**Comment by priceactionful** [comment]
你好朋友
    let kTextAttribute: Dictionary = [NSFontAttributeName: UIFont.systemFontOfSize(12.0)]
   改为
    let kTextAttribute = [NSFontAttributeName: UIFont.systemFontOfSize(12.0)] as Dictionary

**Comment by medisean** [comment]
谢谢
